# Generated by Django 5.0 on 2023-12-25 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_rename_issold_item_is_sold"),
        ("wishlist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="item",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="items",
            field=models.ManyToManyField(related_name="wishlists", to="item.item"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
