# Generated by Django 5.0 on 2023-12-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wishlist", "0002_remove_wishlist_item_wishlist_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="name",
            field=models.CharField(default="wishlist", max_length=255),
            preserve_default=False,
        ),
    ]
